[paper]
type = "Assignment"
module = "ABC123"
title = "Haupttitel der Arbeit"
shortTitle = "Kurztitel"
courseOfStudies = "Software Engineering - Bachelor of Engineering (B. Eng.)"
signupDate = "01.12.2024"
tutor = "Prof. Dr. Tutorin"
lang = "de"                                                                  # ISO 639-1/2/3 language code

[author]
name = "Willy Wesen"
studentId = "123456789"
email = "asd@asd.asd"
street = "Haupstraße 123"
city = "12345 Stadt"
